### ISSUE TITLE
config.ymlについて

### ISSUE THREAD

**Issue by miyamaru-yuuki** [miyamaru-yuuki/omikuji#1]
Unseiエンティティの生成がうまくいかない

**Comment by koharas** [comment]
config.yml を修正して再度githubにアップしてください。
他の修正したファイルも空白がなくなっているようです。

**Comment by miyamaru-yuuki** [comment]
Gitに下記のファイルがないのですがどこかにあるでしょうか？
app/config/parameters.yml

**Comment by koharas** [comment]
parameters.yml.dist です。

**Comment by miyamaru-yuuki** [comment]
空白を足しましたがエラーがなおりません。
まだおかしいところがあるでしょうか？

**Comment by koharas** [comment]
parameters.yml　も必要でしたね。
無いようなら、parameters.yml.distをコピーしてください。

**Comment by miyamaru-yuuki** [comment]
参考にする方のGitにparameters.ymlがないようなのですがインストールからやり直した方がよいでしょうか？

**Comment by koharas** [comment]
parameters.yml.distをコピーしてparameters.ymlにしてください。

**Comment by koharas** [comment]
まず、エラーを貼ってください。画像ファイルはここにドロップすると貼れます。

また、コードは貼った後に選択して<>のボタンを押しください。でないとそのように見出しになったりします（行頭に#があると見出しになります）。
例としてこちらのtemplate.ymlを貼っておきます。
```
# This file is auto-generated during the composer install
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: d06d459a5788d93a46a8937cef97c9916a7bb300
    database_path: "%kernel.root_dir%/../var/data.db3"

```

**Comment by miyamaru-yuuki** [comment]
エラー画像とコードです。

```
# This file is auto-generated during the composer install
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: d06d459a5788d93a46a8937cef97c9916a7bb300
    database_path: "%kernel.root_dir%/../var/data.db3"
```

<img width="682" alt="2019-01-27 11 14 04" src="https://user-images.githubusercontent.com/37493522/51795336-b3aae800-2224-11e9-9a2f-45881a882f2c.png">
